# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

steps:
- task: HCLAppScanOnCloud@2
  inputs:
    AppSecTestService: 'AS360 Local'
    applications: 'a5b7c8c9-b830-4ca3-858b-847a1c26689'
    scanname: 'test'
    scantype: 'dynamic'
    dynamicType: 'DAST'
    scanURL: 'http://demo.testfire.net'
    network: 'public'